version: 2.1
executors:
    default:
        docker:
            - image: circleci/node:latest
        working_directory: ~/repo
commands:
    npm_install:
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: npm install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
    tool_install:
        steps:
            - run: sudo npm i -g can-npm-publish
    npm_lint:
        steps:
          - checkout
          - run: npm run lint
    npm_build:
        steps:
          - checkout
          - run: npm run build
    npm_build_docs:
        steps:
          - checkout
          - run: npm run build-docs
jobs:
    lint:
      executor: default
      steps:
          - npm_install
          - npm_lint
    publish:
        executor: default
        steps:
            - tool_install
            - npm_install
            - npm_build
            - npm_build_docs
            - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
            - run:
                command: |
                    if can-npm-publish; then
                        npm publish
                    else
                        echo "publish skipped"
                    fi
workflows:
    version: 2
    lint:
        jobs:
          - lint
    publishflow:
        jobs:
            - publish:
                context: npm
                filters:
                    branches:
                        only:
                            - master
